version: '3'

networks:

  default:

services:
  php:
    build:
      context: ../
      dockerfile: ./docker/php/Dockerfile
    container_name: php
    networks:
      - default
    ports:
      - '8384:80'
    restart: unless-stopped
    volumes:
      - ../server/:/var/www/html/

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: hub
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - mydb:/var/lib/mysql

volumes:
  mydb: